// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CQRSGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "CQRSGenerator.a7e15de0-8114-4c65-bf96-7eca3e1d6c95";
        public const string Name = "CQRSGenerator";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Ahmed Abdel_Hafeez";
        public const string Tags = "";
    }
}
